### ISSUE TITLE
Separate Python and R

### ISSUE THREAD

**Issue by eeholmes** [boettiger-lab/nasa-topst-env-justice#22]
* Do we want Python and R in the same Quarto doc?

- [x] Separate Python and R; separate page for each. Julie discussed.

<img width="111" alt="image" src="https://github.com/boettiger-lab/nasa-topst-env-justice/assets/2545978/6768af78-51ea-4c1d-971f-07205ddf0894">

- [ ] Folder for each heading in the Cloud Book and each sub heading `how-to`, `find-data` and within that folder `find-python.ipynb`, `find-r.qmd`, etc.

**Comment by cboettig** [comment]
python and R are now separate ipynb / qmd sources in https://boettiger-lab.github.io/nasa-topst-env-justice/

![image](https://github.com/boettiger-lab/nasa-topst-env-justice/assets/222586/74bd0f98-58c9-4ab7-a86f-a4838d8e55e1)


Currently there's only a 'tutorials' section, which I see as more long-form narrative, but will try to start adding a recipes section for a more varied set of minimal examples.  

The following isn't meant as a critique of the openscapes cookbook but just a sketch of my current wrestling with organizational structure for this smaller project.

I've avoided the divisions of 'access data in the cloud' and 'access data locally', as you know, I think this is a bit of a leaky abstraction (does 'in the cloud' mean the compute is in the cloud, or the data is accessed by range request?  In practice, it tends to refer to the compute, which I think is really unfortunate, because now we have lots of examples where the data access patterns still involve downloads and POSIX-based reads but run on rented AWS machines, and this is being marketed as "in the cloud" and "better", whereas I would like to promote workflows that work identically regardless of the compute and use 'cloud native' data reads.   it's also important to me that most of the workflow is identical whether we are downloading files and reading over POSIX or streaming data over HTTP, most of the time the user shouldn't care about this anyway, and thus shouldn't be asking themselves "do I want cloud or local access", but simply "i want access" that fast, reproducible, portable, etc.  

"find data" is obviously an important topic but not something I see as inherently computational that needs 'python' and 'R' flavors.  I will try and write something thoughts on this, though it's obviously a messy problem and still very discipline-specific.
